name: tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          cp .env.example .env
          echo "DB_HOST=mysql" >> .env
          echo "DB_USERNAME=sail" >> .env
          echo "DB_PASSWORD=password" >> .env
          echo "DB_DATABASE=laravel" >> .env
          ./vendor/bin/sail up -d

      - name: Wait for MySQL
        run: sleep 15

      - name: Install Composer Dependencies
        run: ./vendor/bin/sail composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: ./vendor/bin/sail php artisan key:generate

      - name: Publish Ziggy Configuration
        run: ./vendor/bin/sail php artisan ziggy:generate

      - name: Build Assets
        run: ./vendor/bin/sail npm run build

      - name: Run Tests
        run: ./vendor/bin/sail pest
